taxi_dbt_project:
  target: dev
  outputs:
    dev:
      type: snowflake
      account: "{{ env_var('DBT_snowflake_account') }}"
      user: "{{ env_var('DBT_snowflake_user') }}"
      password: "{{ env_var('DBT_snowflake_pwd') }}"
      role: "{{ env_var('DBT_snowflake_role') }}"
      database: "{{ env_var('DBT_snowflake_database') }}"
      warehouse: "{{ env_var('DBT_snowflake_warehouse') }}"
      schema: "{{ env_var('DBT_snowflake_schema') }}"
      threads: 4
      client_session_keep_alive: false
